### ISSUE TITLE
Benchmark for UWebsockets

### ISSUE THREAD

**Issue by PXshadow** [djaonourside/uwebsockets-externs#1]
Hey! I've been benchmarking as many nodejs libraries as I could and got pointed to your externs. I wrote up a quick benchmark and was very impressed by the performance, thought I'd share it here. Well done on the externs I think it's the best choice for a web server http or websockets on nodejs 😃 
![image](https://user-images.githubusercontent.com/9813078/93950849-86fceb80-fcf9-11ea-8380-a8bbda7fe98b.png)

**Comment by djaonourside** [comment]
@PXshadow can you add pure js test here?

**Comment by PXshadow** [comment]
Yeah sure I'll post it here tommrow, just saw the discussion on uwebsockets.js sorry if i caused any turmoil my apologies.

**Comment by djaonourside** [comment]
Thank you @PXshadow . I think it's not about you, it's about people's stereotypic mind :)

**Comment by PXshadow** [comment]
Here you go, I hope this helps here is the [benchmark repo as well](https://github.com/PXshadow/weblinkBenchmark) if you want to check the code. As I expected it's essentially the same speed in haxe vs js.


![image](https://user-images.githubusercontent.com/9813078/94084295-0eaa2f00-fdba-11ea-921a-e3711e6bc175.png)

**Comment by djaonourside** [comment]
@PXshadow Thank you very much. I am trying to write cpp/hashlink externs for uwebsockets. Suppose the speed will increase more.

**Comment by PXshadow** [comment]
Yes i would think so 😊, let me know when you have those externs I would be super excited to use those externs and hopefully also make weblink more performant and support cpp before haxe 4.2
